config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :product_categories
  resource :orders, only: :show
  resources :order_details

  resources :products do
    resources :reviews, only: %i[index new create destroy]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  before_destroy :not_referenced_by_any_order_detail
  # products = Product.all
  # list = []
  # products.each do |p|
  #   list << p.id
  # end
  # PRODUCTS = list

  has_many :reviews, dependent: :destroy
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories

  has_many :order_details

  private

  def not_referenced_by_any_order_detail
    unless order_details.empty?
      errors.add(:base, 'Order details present')
      throw :abort
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: %i[edit update show destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]
  # skip_after_action :verify_authorized, only: [:show]

  def index
    @products = policy_scope(Product)
    @order_detail = current_order.order_details.new
  end

  def show
    product_category
    authorize @product
  end

  def new
    @product = Product.new
    authorize @product
  end

  def create
    @product = Product.new(product_params)
    authorize @product

    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def edit
    authorize @product
  end

  def update
    @product.update(product_params)
    authorize @product
    redirect_to product_path(@product)
  end

  def destroy
    @product.destroy
    authorize @product
    redirect_to products_path
  end

  private

  def product_category
    @product_categories = ProductCategory.where(product_id: @product.id)
  end

  def find_product
    @product = Product.find_by_id(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :price, :amount, :category, :photo)
  end
end

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= simple_form_for @product do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :amount %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/products/index.html.erb
<h1>Here are all products</h1>

<%= link_to 'Home', root_path  %>
<%= link_to "#{current_order.order_details.size} items with a value of EUR ...", orders_path  %>


<ul>
  <% @products.each do |p| %>
    <li>
      <%= p.title %>
      <p>Eur <%= p.price %></p>
      <%= link_to 'Show', product_path(p)  %>
      <%= form_for @order_detail do |f| %>
        <%= f.hidden_field :product_id, :value => p.id %>
        <%= f.number_field :ammount, :value => 1, :min => 1 %>
        <%= f.submit "Add to cart" %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/products/new.html.erb
<h1>Add a new product here</h1>

<%= simple_form_for [@product] do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :amount %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/products/show.html.erb
<h1>This is my product</h1>
<%= @product.title %>

<p>This products belongs to the categories:</p>
<ul>
  <% @product_categories.each do |pc| %>
    <li>
      <%= pc.category.title %>
      <% if policy(@product).destroy? %>
        <%= link_to "delete category", product_category_path(pc), method: :delete %>
      <% end %>
    </li>
  <% end %>
</ul>


<% if user_signed_in? %>
  <% if policy(@product).destroy? %>
    <%= link_to "delete", product_path(@product), method: :delete %>
    <%= link_to "edit", edit_product_path(@product) %>
    <%= link_to "Add Category", new_product_category_path %>
  <% end %>
<% end %>


<%= button_to 'Add to cart', order_detail_path(product_id: @product), class: 'btn btn-primary'%>


<%= link_to 'Home', root_path  %>
<%= link_to 'Back', :back %>